version: "3"

services:
  node-1:
    image: openraft-rocksdb
    ports:
      - 21001:21000
    environment:
      - NODE_ID=1
      - RUST_LOG=info
      - COMPACTION_STYLE=${COMPACTION_STYLE:-1}
    volumes:
      - ~/study/tcc/raft/node-logs:/usr/src/raft/logs
    build:
      context: .
      dockerfile: Dockerfile

  node-2:
    image: openraft-rocksdb
    ports:
      - 21002:21000
    environment:
      - NODE_ID=2
      - RUST_LOG=info
      - COMPACTION_STYLE=${COMPACTION_STYLE:-1}
    volumes:
      - ~/study/tcc/raft/node-logs:/usr/src/raft/logs

  node-3:
    image: openraft-rocksdb
    ports:
      - 21003:21000
    environment:
      - NODE_ID=3
      - RUST_LOG=info
      - COMPACTION_STYLE=${COMPACTION_STYLE:-1}
    volumes:
      - ~/study/tcc/raft/node-logs:/usr/src/raft/logs
